[package]
name = "rs-cache"
version = "0.2.4"
authors = ["jimvdl <jimvdlind@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A simple RuneScape cache utility."
repository = "https://github.com/jimvdl/rs-cache"
documentation = "https://docs.rs/rs-cache"
readme = "README.md"
keywords = ["runescape", "osrs"]
exclude = [".gitignore", "data/cache"]

[lib]
name = "rscache"
path = "src/lib.rs"

[dependencies]
crc = "1.8.1"
bzip2 = "0.3.3"
libflate = "0.1.27"

[dev-dependencies]
sha1 = "0.6.0"