[package]
name = "rs-cache"
version = "0.1.1"
authors = ["jimvdl <jimvdlind@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A simple RuneScape cache utility."
repository = "https://github.com/jimvdl/rs-cache"

[dependencies]